var l14406e = [
"Feedback and cleaning2m.",
"Welcome back.",
"By now it's safe to say that verifying, documenting and reporting are valuable steps in the data-cleaning process.",
"You have proof to give stakeholders that your data is accurate and reliable.",
"And the effort to attain it was well-executed and documented.",
"The next step is getting feedback about the evidence and using it for good, which we'll cover in this video.",
"Clean data is important to the task at hand.",
"But the data-cleaning process itself can reveal insights that are helpful to a business.",
"The feedback we get when we report on our cleaning can transform data collection processes, and ultimately business development.",
"For example, one of the biggest challenges of working with data is dealing with errors.",
"Some of the most common errors involve human mistakes like mistyping or misspelling, flawed processes like poor design of a survey form, and system issues where older systems integrate data incorrectly.",
"Whatever the reason, data-cleaning can shine a light on the nature and severity of error-generating processes.",
"With consistent documentation and reporting, we can uncover error patterns in data collection and entry procedures and use the feedback we get to make sure common errors aren't repeated.",
"Maybe we need to reprogram the way the data is collected or change specific questions on the survey form.",
"In more extreme cases, the feedback we get can even send us back to the drawing board to rethink expectations and possibly update quality control procedures.",
"For example, sometimes it's useful to schedule a meeting with a data engineer or data owner to make sure the data is brought in properly and doesn't require constant cleaning.",
"Once errors have been identified and addressed, stakeholders have data they can trust for decision-making.",
"And by reducing errors and inefficiencies in data collection, the company just might discover big increases to its bottom line.",
"Congratulations!",
"You now have the foundation you need to successfully verify a report on your cleaning results.",
"Stay tuned to keep building on your new skills.",
]