var l41110e = [
"Face to Face Office Hours - Bletchley Park5m.",
"Chuck here, it's 2019 and we've been to Bletchley Park it seems every odd-numbered year, about spring, although it's really beautiful, the trees are blooming.",
"But once again, we're at Bletchley Park and so I'd like you to meet some of your fellow students.",
"So here we go.",
"Hello there.",
"Hi, my name is Cata Lyman.",
"I coming from Romania.",
"I tutor History class and I use the Python for Everybody to teach other fellow colleagues how to code in Python.",
"So how many students have you taught to teach Python in Romania?",
"Over 100 and I will send you some cool pictures with them.",
"I'll put some pictures in this video.",
"So you send me the pictures and I'll put some of the pictures of you teaching Python in the video.",
"Thank you very much.",
"Thank you.",
"Hello everybody.",
"My name is Carina Seviano.",
"I'm originally from Peru, but live in London.",
"So I am a supply chain professional who is looking to use Python and all their tools in order to solve the supply chain problems.",
"So very interested and thank you.",
"I am in the Python for Everybody specialization.",
"I have just finished the first course, so I'm looking forward to continue with the second and the next ones.",
"Thanks.",
"Thank you.",
"Hello, I'm Maria and I'm originally from Russia.",
"I now live in London.",
"I finished the Python for Informatics course in 2015 and since then, I wanted to meet Dr. Chuck.",
"Well, here you are.",
"And I must say that the specialization ended me indirectly up in Google.",
"So now work for Google in London.",
"You work for Google?",
"Yes.",
"Oh, wow, congratulations.",
"Thank you.",
"Hi.",
"I'm Cholten from Copenhagen, Denmark.",
"I took the Internet course and I use some of the materials from the surroundings to make papers on how to see how technology, human, and innovation can interact.",
"And you actually traveled from Copenhagen?",
"Yeah, I flew in yesterday.",
"For this?",
"For this.",
"Yeah.",
"That's impressive.",
"Thank you.",
"Hi, I am Olivia and I live pretty close to here.",
"You didn't fly in?",
"No, I just drove in.",
"I do the Python for Everybody course.",
"I'm almost finished.",
"So I'm a marine biologist.",
"I'm using Python to study sponge genomes.",
"That's the plan.",
"Yeah, so I'm hoping I'm going to get a PhD out of this course on my CV.",
"That's really cool.",
"Python can be used for anything.",
"Yeah.",
"Like sponges.",
"Yeah.",
"Sponges.",
"Hi, my name is Amani.",
"I am from Brighton.",
"I took Internet Technology course and Python for Everybody.",
"I'm a PhD candidate in the University of Sussex.",
"What's your topic?",
"Cloud computing and vehicular networks.",
"Vehicular networks?",
"Yeah.",
"You know, I have a theory.",
"My theory is that if we just put WiFi on all the cars, then they would broadcast their locations to each other.",
"Yeah, well, this is what we're working on.",
"Yeah.",
"Connected cars.",
"Yeah, if the cars just would know where the other cars are at, it would kind of be helpful.",
"Yeah, you're right.",
"Of course.",
"That's cool.",
"So we're going to do it.",
"Why not?",
"Hello, I'm Yannis.",
"I'm originally from Greece, but I'm living in London.",
"I'm in Computer Science, but I really enjoyed that course and I'm suggesting it here and there to friends not related to IT.",
"That's why I'm here for it.",
"Cool.",
"Thank you very much for inviting us.",
"Hi I'm Marian and I am originally from Greece, but I live in London.",
"Programming is a hobby for me, and really very much enjoyed the course.",
"You're welcome.",
"Last year.",
"Thank you very much.",
"Hi, I'm Martin from London.",
"I'm a gentleman of leisure, but I decided to take the Python for Everybody course just to keep my brain from going to pulp.",
"I'm very pleased I managed to just get there.",
"We'll keep making more specializations so that your brain will never turn into pulp.",
"Hi, I'm Steve.",
"I'm one of your TAs for Python in the Capstone and Web Applications for Everybody course.",
"Yeah.",
"So this is the third time that Steve and I have met in Bletchley.",
"But a week ago, we were in Michigan.",
"I brought Stephen in for the fifth anniversary celebration that we had on campus in Ann Arbor.",
"So let's everybody give a big round of applause for Stephen and all the work that he does.",
"Okay. so I believe my next trip, well, two things.",
"First, I'm going straight from London to go car racing and I want to invite everybody to visit me at the car track in Illinois, but you probably won't make it to the car racing track in Illinois.",
"But South Africa is the next place that I'll probably end up meeting students.",
"So hopefully I'll see you in South Africa.",
"Cheers.",
]