var l41205e = [
"Face to Face Office Hours - Tokyo2m.",
"Hello, everybody, it's Chuck and here we are in Tokyo just like I promised in the last video that we would find my way to Tokyo.",
"It's surprising that I've not been here since the MOOC started in 2012 but we finally made it.",
"So like always, I want to let you meet some of the other students in class.",
"So they'll tell you their name and maybe a little bit of message, okay?",
"So let's go ahead and start with you.",
"My name is Christian.",
"Dr.Chuck teaches me, I teach my students.",
"Thank you, Dr.Chuck.",
"I love it when teachers teach programming.",
"To what age?",
"I teach middle school and high school students.",
"Great.",
"Hi, I'm [inaudible], Dr.Chuck, I appreciate for your great, great, excellent class.",
"Thank you very much.",
"I appreciate that you came and it's been great talking to you.",
"I'm Ben.",
"I'm originally from Australia and I've really enjoyed taking all your courses, Dr.Chuck.",
"So thank you.",
"Thank you.",
"Emmanuel, from Uganda, at Tokyo University of Agriculture currently.",
"It's been a pleasure doing Dr.Chuck's course.",
"I will use it in hydrologic modeling and teach my laboratory mates Python since most know MATLAB.",
"Thank you so much, Dr.Chuck.",
"Welcome to the class.",
"Sure.",
"Hey, my name is Ahmed.",
"I'm from Tunisia.",
"I enjoyed a lot doing Python classes.",
"Now, it's great honor to meet with Dr.Chuck.",
"Thank you a lot and I hope to keep continuing with you.",
"Thank you.",
"My name is Jen, I'm from India.",
"I'm learning Python in the right way from Dr.Chuck.",
"Thank you very much.",
"Thank you.",
"Hi, my name is [inaudible], I use your course every day for Data Science and thanks a lot for all those courses.",
"Thanks.",
"Thank you.",
"Hi, I'm Hiro.",
"This is first time experience to virtual reality becomes real.",
"Thank you.",
"Thanks.",
"Hey, my name is Sheila and I'm taking Python.",
"I'm really enjoying learning a new program language and I'm grateful for this course.",
"Thank you.",
"Thanks for coming.",
"Hi, I'm [inaudible] I'm learning Python For Everybody.",
"I love Python and I love Dr.Chuck.",
"Thank you.",
"Thank you.",
"So there we go, up next in a couple of days we'll be in Nagoya.",
"So two in Japan after five years of not being here.",
"See you on the net.",
"Cheers.",
]