var l41505e = [
"Face to Face Office Hours - Kitchener, Ontario2m.",
"Hello, everybody.",
"Here we are in Kitchener, Ontario.",
"I'm here working with Learning Management System vendor called Desire to Learn, to help them work on their implementation of a protocol called Learning Tools Interoperability, which turns out to be the way the autograder sends grades back to Coursera.",
"So I want you to meet some of your fellow students, and they can talk a little bit about the course and tell us their name.",
"Hi, [inaudible] , I finished the first four courses with Python for Everybody.",
"I'm waiting for the capstone.",
"Hopefully, things go excellent.",
"Thank you.",
"Hey, how is the going?",
"Louis de Bruijn, I just finished the first two courses of Python there, and super stoked looking Dr.Chuck and the rest of the community in learning Python, and looking forward to continue learning with the Coursera products.",
"Thanks for coming up from Toronto.",
"Yeah, no worries.",
"Hi.",
"My name is Giga, I'm doing the Python for Everybody course and completed the first two courses of Python, and super excited to do the third one, as well as the capstone course.",
"Thanks to Chuck.",
"Cheers.",
"Hey, I'm Herman, I'm doing Python for Everybody from Coursera and I am on course 2, and it's really exciting.",
"Cheers.",
"Hi, I'm Dave.",
"I just finished Python for Everybody and the Web Design for Everybody, and I'm looking forward to doing the Django course when it's available.",
"Cool.",
"Yeah.",
"So I don't know where I'm going to see you next.",
"It's coming up on on-campus teaching in the fall of this semester, and I'm teaching Django class, which I hope to turn into Django for Everybody in upcoming.",
"So I'm going to be busy building autograders and all those things for my Django class.",
"I hope to see you sooner or later at an upcoming office-hours.",
"Cheers.",
]