let objs02 = [
 {
  "name": "1 Change the Color of Text",
  "code": [
   "<h2 style=\"color: red;\">CatPhotoApp</h2>",
   "<main>",
   "  <p>Click here to view more <a href=\"#\">cat photos</a>.</p>",
   "",
   "  <a href=\"#\"><img src=\"https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg\" alt=\"A cute orange cat lying on its back.\"></a>",
   "",
   "  <div>",
   "    <p>Things cats love:</p>",
   "    <ul>",
   "      <li>cat nip</li>",
   "      <li>laser pointers</li>",
   "      <li>lasagna</li>",
   "    </ul>",
   "    <p>Top 3 things cats hate:</p>",
   "    <ol>",
   "      <li>flea treatment</li>",
   "      <li>thunder</li>",
   "      <li>other cats</li>",
   "    </ol>",
   "  </div>",
   "",
   "  <form action=\"https://freecatphotoapp.com/submit-cat-photo\">",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\" checked> Indoor</label>",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\"> Outdoor</label><br>",
   "    <label><input type=\"checkbox\" name=\"personality\" checked> Loving</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Lazy</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Energetic</label><br>",
   "    <input type=\"text\" placeholder=\"cat photo URL\" required>",
   "    <button type=\"submit\">Submit</button>",
   "  </form>",
   "</main>"
  ]
 },
 {
  "name": "2 Use CSS Selectors to Style Elements",
  "code": [
   "<style>",
   "  h2 {",
   "    color: blue;",
   "  }",
   "</style>",
   ""
  ]
 },
 {
  "name": "3 Use a CSS Class to Style an Element",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "</style>",
   "",
   "<h2 class=\"red-text\">CatPhotoApp</h2>",
   "<main>",
   "  <p>Click here to view more <a href=\"#\">cat photos</a>.</p>",
   "",
   "  <a href=\"#\"><img src=\"https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg\" alt=\"A cute orange cat lying on its back.\"></a>",
   "",
   "  <div>",
   "    <p>Things cats love:</p>",
   "    <ul>",
   "      <li>cat nip</li>",
   "      <li>laser pointers</li>",
   "      <li>lasagna</li>",
   "    </ul>",
   "    <p>Top 3 things cats hate:</p>",
   "    <ol>",
   "      <li>flea treatment</li>",
   "      <li>thunder</li>",
   "      <li>other cats</li>",
   "    </ol>",
   "  </div>",
   "",
   "  <form action=\"https://freecatphotoapp.com/submit-cat-photo\">",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\" checked> Indoor</label>",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\"> Outdoor</label><br>",
   "    <label><input type=\"checkbox\" name=\"personality\" checked> Loving</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Lazy</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Energetic</label><br>",
   "    <input type=\"text\" placeholder=\"cat photo URL\" required>",
   "    <button type=\"submit\">Submit</button>",
   "  </form>",
   "</main>"
  ]
 },
 {
  "name": "4 Style Multiple Elements with a CSS Class",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "</style>",
   "",
   "<h2 class=\"red-text\">CatPhotoApp</h2>",
   "<main>",
   "  <p class=\"red-text\">Click here to view more <a href=\"#\">cat photos</a>.</p>",
   "",
   "  <a href=\"#\"><img src=\"https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg\" alt=\"A cute orange cat lying on its back.\"></a>",
   "",
   "  <div>",
   "    <p>Things cats love:</p>",
   "    <ul>",
   "      <li>cat nip</li>",
   "      <li>laser pointers</li>",
   "      <li>lasagna</li>",
   "    </ul>",
   "    <p>Top 3 things cats hate:</p>",
   "    <ol>",
   "      <li>flea treatment</li>",
   "      <li>thunder</li>",
   "      <li>other cats</li>",
   "    </ol>",
   "  </div>",
   "",
   "  <form action=\"https://freecatphotoapp.com/submit-cat-photo\">",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\" checked> Indoor</label>",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\"> Outdoor</label><br>",
   "    <label><input type=\"checkbox\" name=\"personality\" checked> Loving</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Lazy</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Energetic</label><br>",
   "    <input type=\"text\" placeholder=\"cat photo URL\" required>",
   "    <button type=\"submit\">Submit</button>",
   "  </form>",
   "</main>"
  ]
 },
 {
  "name": "5 Change the Font Size of an Element",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "  p {",
   "    font-size: 16px;",
   "  }",
   "</style>",
   "",
   "<h2 class=\"red-text\">CatPhotoApp</h2>",
   "<main>",
   "  <p class=\"red-text\">Click here to view more <a href=\"#\">cat photos</a>.</p>",
   "",
   "  <a href=\"#\"><img src=\"https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg\" alt=\"A cute orange cat lying on its back.\"></a>",
   "",
   "  <div>",
   "    <p>Things cats love:</p>",
   "    <ul>",
   "      <li>cat nip</li>",
   "      <li>laser pointers</li>",
   "      <li>lasagna</li>",
   "    </ul>",
   "    <p>Top 3 things cats hate:</p>",
   "    <ol>",
   "      <li>flea treatment</li>",
   "      <li>thunder</li>",
   "      <li>other cats</li>",
   "    </ol>",
   "  </div>",
   "",
   "  <form action=\"https://freecatphotoapp.com/submit-cat-photo\">",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\" checked> Indoor</label>",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\"> Outdoor</label><br>",
   "    <label><input type=\"checkbox\" name=\"personality\" checked> Loving</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Lazy</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Energetic</label><br>",
   "    <input type=\"text\" placeholder=\"cat photo URL\" required>",
   "    <button type=\"submit\">Submit</button>",
   "  </form>",
   "</main>"
  ]
 },
 {
  "name": "6 Set the Font Family of an Element",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "",
   "  p {",
   "    font-family: monospace;",
   "    font-size: 16px;",
   "  }",
   "</style>",
   ""
  ]
 },
 {
  "name": "7 Import a Google Font",
  "code": [
   "<link href=\"https://fonts.googleapis.com/css?family=Lobster\" rel=\"stylesheet\" type=\"text/css\"> ",
   "<style>",
   "  font-family: Lobster, \"Open Sans\";",
   "  .red-text {",
   "    color: red;",
   "  }",
   "",
   "  h2 {",
   "    font-family: Lobster;",
   "  }",
   "",
   "  p {",
   "    font-size: 16px;",
   "    font-family: monospace;",
   "  }",
   "</style>",
   ""
  ]
 },
 {
  "name": "8 Specify How Fonts Should Degrade",
  "code": [
   "<!-- <link href=\"https://fonts.googleapis.com/css?family=Lobster\" rel=\"stylesheet\" type=\"text/css\"> -->",
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "",
   "  h2 {",
   "    font-family: Lobster, monospace;",
   "  }",
   "",
   "  p {",
   "    font-size: 16px;",
   "    font-family: monospace;",
   "  }",
   "</style>",
   ""
  ]
 },
 {
  "name": "9 Size Your Images",
  "code": [
   "<link href=\"https://fonts.googleapis.com/css?family=Lobster\" rel=\"stylesheet\" type=\"text/css\">",
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "",
   "  h2 {",
   "    font-family: Lobster, monospace;",
   "  }",
   "",
   "  p {",
   "    font-size: 16px;",
   "    font-family: monospace;",
   "  }",
   "",
   "  .smaller-image {",
   "    width: 100px;",
   "  }",
   "</style>",
   "",
   "<h2 class=\"red-text\">CatPhotoApp</h2>",
   "<main>",
   "  <p class=\"red-text\">Click here to view more <a href=\"#\">cat photos</a>.</p>",
   "",
   "  <a href=\"#\"><img class=\"smaller-image\" src=\"https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg\" alt=\"A cute orange cat lying on its back.\"></a>",
   "",
   "  <div>",
   "    <p>Things cats love:</p>",
   "    <ul>",
   "      <li>cat nip</li>",
   "      <li>laser pointers</li>",
   "      <li>lasagna</li>",
   "    </ul>",
   "    <p>Top 3 things cats hate:</p>",
   "    <ol>",
   "      <li>flea treatment</li>",
   "      <li>thunder</li>",
   "      <li>other cats</li>",
   "    </ol>",
   "  </div>",
   "",
   "  <form action=\"https://freecatphotoapp.com/submit-cat-photo\">",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\" checked> Indoor</label>",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\"> Outdoor</label><br>",
   "    <label><input type=\"checkbox\" name=\"personality\" checked> Loving</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Lazy</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Energetic</label><br>",
   "    <input type=\"text\" placeholder=\"cat photo URL\" required>",
   "    <button type=\"submit\">Submit</button>",
   "  </form>",
   "</main>"
  ]
 },
 {
  "name": "10 Add Borders Around Your Elements",
  "code": [
   "  .thick-green-border {",
   "    border: solid 10px green;",
   "  }",
   ""
  ]
 },
 {
  "name": "11 Add Rounded Corners with border-radius",
  "code": [
   "  .thick-green-border {",
   "    border-color: green;",
   "    border-width: 10px;",
   "    border-style: solid;",
   "    border-radius: 10px;",
   "  }",
   ""
  ]
 },
 {
  "name": "12 Make Circular Images with a border-radius",
  "code": [
   "  .thick-green-border {",
   "    border-color: green;",
   "    border-width: 10px;",
   "    border-style: solid;",
   "    border-radius: 50%;",
   "  }",
   ""
  ]
 },
 {
  "name": "13 Give a Background Color to a div Element",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "",
   "  h2 {",
   "    font-family: Lobster, monospace;",
   "  }",
   "",
   "  p {",
   "    font-size: 16px;",
   "    font-family: monospace;",
   "  }",
   "",
   "  .thick-green-border {",
   "    border-color: green;",
   "    border-width: 10px;",
   "    border-style: solid;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .smaller-image {",
   "    width: 100px;",
   "  }",
   "",
   "  .silver-background {",
   "    background-color: silver;",
   "  }",
   "</style>",
   ""
  ]
 },
 {
  "name": "14 Set the id of an Element",
  "code": [
   "  <form id=\"cat-photo-form\" action=\"https://freecatphotoapp.com/submit-cat-photo\">",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\" checked> Indoor</label>",
   "    <label><input type=\"radio\" name=\"indoor-outdoor\"> Outdoor</label><br>",
   "    <label><input type=\"checkbox\" name=\"personality\" checked> Loving</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Lazy</label>",
   "    <label><input type=\"checkbox\" name=\"personality\"> Energetic</label><br>",
   "    <input type=\"text\" placeholder=\"cat photo URL\" required>",
   "    <button type=\"submit\">Submit</button>",
   "  </form>",
   ""
  ]
 },
 {
  "name": "15 Use an id Attribute to Style an Element",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "",
   "  h2 {",
   "    font-family: Lobster, monospace;",
   "  }",
   "",
   "  p {",
   "    font-size: 16px;",
   "    font-family: monospace;",
   "  }",
   "",
   "  .thick-green-border {",
   "    border-color: green;",
   "    border-width: 10px;",
   "    border-style: solid;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .smaller-image {",
   "    width: 100px;",
   "  }",
   "",
   "  .silver-background {",
   "    background-color: silver;",
   "  }",
   "",
   "  #cat-photo-form {",
   "    background-color: green;",
   "  }",
   "</style>",
   ""
  ]
 },
 {
  "name": "16 Adjust the Padding of an Element",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: red;",
   "  }",
   "",
   "  h2 {",
   "    font-family: Lobster, monospace;",
   "  }",
   "",
   "  p {",
   "    font-size: 16px;",
   "    font-family: monospace;",
   "  }",
   "",
   "  .thick-green-border {",
   "    border-color: green;",
   "    border-width: 10px;",
   "    border-style: solid;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .smaller-image {",
   "    width: 100px;",
   "  }",
   "",
   "  .silver-background {",
   "    background-color: silver;",
   "  }",
   "",
   "  #cat-photo-form {",
   "    background-color: green;",
   "  }",
   "</style>",
   ""
  ]
 },
 {
  "name": "17 Adjust the Margin of an Element",
  "code": [
   "<style>",
   "  .injected-text {",
   "    margin-bottom: -25px;",
   "    text-align: center;",
   "  }",
   "",
   "  .box {",
   "    border-style: solid;",
   "    border-color: black;",
   "    border-width: 5px;",
   "    text-align: center;",
   "  }",
   "",
   "  .yellow-box {",
   "    background-color: yellow;",
   "    padding: 10px;",
   "  }",
   "",
   "  .red-box {",
   "    background-color: crimson;",
   "    color: #fff;",
   "    padding: 20px;",
   "    margin: 20px;",
   "  }",
   "",
   "  .blue-box {",
   "    background-color: blue;",
   "    color: #fff;",
   "    padding: 20px;",
   "    margin: 20px;",
   "  }",
   "</style>",
   "<h5 class=\"injected-text\">margin</h5>",
   "",
   "<div class=\"box yellow-box\">",
   "  <h5 class=\"box red-box\">padding</h5>",
   "  <h5 class=\"box blue-box\">padding</h5>",
   "</div>"
  ]
 },
 {
  "name": "18 Add a Negative Margin to an Element",
  "code": [
   "<style>",
   "  .injected-text {",
   "    margin-bottom: -25px;",
   "    text-align: center;",
   "  }",
   "",
   "  .box {",
   "    border-style: solid;",
   "    border-color: black;",
   "    border-width: 5px;",
   "    text-align: center;",
   "  }",
   "",
   "  .yellow-box {",
   "    background-color: yellow;",
   "    padding: 10px;",
   "  }",
   "",
   "  .red-box {",
   "    background-color: crimson;",
   "    color: #fff;",
   "    padding: 20px;",
   "    margin: -15px;",
   "  }",
   "",
   "  .blue-box {",
   "    background-color: blue;",
   "    color: #fff;",
   "    padding: 20px;",
   "    margin: -15px;",
   "  }",
   "</style>",
   "",
   "<div class=\"box yellow-box\">",
   "  <h5 class=\"box red-box\">padding</h5>",
   "  <h5 class=\"box blue-box\">padding</h5>",
   "</div>"
  ]
 },
 {
  "name": "19 Add Different Padding to Each Side of an Element",
  "code": [
   "<style>",
   "  .injected-text {",
   "    margin-bottom: -25px;",
   "    text-align: center;",
   "  }",
   "",
   "  .box {",
   "    border-style: solid;",
   "    border-color: black;",
   "    border-width: 5px;",
   "    text-align: center;",
   "  }",
   "",
   "  .yellow-box {",
   "    background-color: yellow;",
   "    padding: 10px;",
   "  }",
   "",
   "  .red-box {",
   "    background-color: crimson;",
   "    color: #fff;",
   "    padding-top: 40px;",
   "    padding-right: 20px;",
   "    padding-bottom: 20px;",
   "    padding-left: 40px;",
   "  }",
   "",
   "  .blue-box {",
   "    background-color: blue;",
   "    color: #fff;",
   "    padding: 40px 20px 20px 40px;",
   "  }",
   "</style>",
   "<h5 class=\"injected-text\">margin</h5>",
   "",
   "<div class=\"box yellow-box\">",
   "  <h5 class=\"box red-box\">padding</h5>",
   "  <h5 class=\"box blue-box\">padding</h5>",
   "</div>"
  ]
 },
 {
  "name": "20 Add Different Margins to Each Side of an Element",
  "code": [
   "  .blue-box {",
   "    background-color: blue;",
   "    color: #fff;",
   "    /* margin: 40px 20px 20px 40px; */",
   "    margin-top: 40px;",
   "    margin-right: 20px;",
   "    margin-bottom: 20px;",
   "    margin-left: 40px;",
   "  }",
   ""
  ]
 },
 {
  "name": "21 Use Clockwise Notation to Specify the Padding of an Element",
  "code": [
   "  .blue-box {",
   "    background-color: blue;",
   "    color: #fff;",
   "    padding: 40px 20px 20px 40px;",
   "  }",
   ""
  ]
 },
 {
  "name": "22 Use Clockwise Notation to Specify the Margin of an Element",
  "code": [
   "  .blue-box {",
   "    background-color: blue;",
   "    color: #fff;",
   "    margin: 40px 20px 20px 40px;",
   "  }",
   ""
  ]
 },
 {
  "name": "23 Use Attribute Selectors to Style Elements",
  "code": [
   "  [type='checkbox'] {",
   "    margin-top: 10px;",
   "    margin-bottom: 15px;",
   "  }",
   ""
  ]
 },
 {
  "name": "24 Understand Absolute versus Relative Units",
  "code": [
   "  .red-box {",
   "    background-color: red;",
   "    padding: 1.5em;",
   "    margin: 20px 40px 20px 40px;",
   "",
   "  }"
  ]
 },
 {
  "name": "25 Style the HTML Body Element",
  "code": [
   "<style>",
   "  body {",
   "    background: black;",
   "  }",
   "",
   "</style>",
   ""
  ]
 },
 {
  "name": "26 Inherit Styles from the Body Element",
  "code": [
   "<style>",
   "  body {",
   "    font-family: monospace;",
   "    background-color: black;",
   "    color: green;",
   "  }",
   "",
   "</style>",
   "<h1>Hello World</h1>"
  ]
 },
 {
  "name": "27 Prioritize One Style Over Another",
  "code": [
   "<style>",
   "  body {",
   "    background-color: black;",
   "    font-family: monospace;",
   "    color: green;",
   "  }",
   "",
   "  .pink-text {",
   "    color: pink;",
   "  }",
   "</style>",
   "<h1 class=\"pink-text\">Hello World!</h1>"
  ]
 },
 {
  "name": "28 Override Styles in Subsequent CSS",
  "code": [
   "<style>",
   "  body {",
   "    background-color: black;",
   "    font-family: monospace;",
   "    color: green;",
   "  }",
   "  .pink-text {",
   "    color: pink;",
   "  }",
   "  .blue-text {",
   "    color: blue;",
   "  }",
   "</style>",
   "<h1 class=\"pink-text blue-text\">Hello World!</h1>"
  ]
 },
 {
  "name": "29 Override Class Declarations by Styling ID Attributes",
  "code": [
   "<style>",
   "  body {",
   "    background-color: black;",
   "    font-family: monospace;",
   "    color: green;",
   "  }",
   "  #orange-text {",
   "    color: orange;",
   "  }",
   "  .pink-text {",
   "    color: pink;",
   "  }",
   "  .blue-text {",
   "    color: blue;",
   "  }",
   "</style>",
   "<h1 id=\"orange-text\" class=\"pink-text blue-text\">Hello World!</h1>"
  ]
 },
 {
  "name": "30 Override Class Declarations with Inline Styles",
  "code": [
   "<style>",
   "  body {",
   "    background-color: black;",
   "    font-family: monospace;",
   "    color: green;",
   "  }",
   "  #orange-text {",
   "    color: orange;",
   "  }",
   "  .pink-text {",
   "    color: pink;",
   "  }",
   "  .blue-text {",
   "    color: blue;",
   "  }",
   "</style>",
   "<h1 id=\"orange-text\" class=\"pink-text blue-text\" style=\"color: white;\">Hello World!</h1>"
  ]
 },
 {
  "name": "31 Override All Other Styles by using Important",
  "code": [
   "<style>",
   "  body {",
   "    background-color: black;",
   "    font-family: monospace;",
   "    color: green;",
   "  }",
   "  #orange-text {",
   "    color: orange;",
   "  }",
   "  .pink-text {",
   "    color: pink !important;",
   "  }",
   "  .blue-text {",
   "    color: blue;",
   "  }",
   "</style>",
   "<h1 id=\"orange-text\" class=\"pink-text blue-text\" style=\"color: white\">Hello World!</h1>"
  ]
 },
 {
  "name": "32 Use Hex Code for Specific Colors",
  "code": [
   "<style>",
   "  body {",
   "    background-color: #000000;",
   "  }",
   "</style>"
  ]
 },
 {
  "name": "33 Use Hex Code to Mix Colors",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: #FF0000;",
   "  }",
   "  .green-text {",
   "    color: #00FF00;",
   "  }",
   "  .dodger-blue-text {",
   "    color: #1E90FF;",
   "  }",
   "  .orange-text {",
   "    color: #FFA500;",
   "  }",
   "</style>",
   "",
   "<h1 class=\"red-text\">I am red!</h1>",
   "",
   "<h1 class=\"green-text\">I am green!</h1>",
   "",
   "<h1 class=\"dodger-blue-text\">I am dodger blue!</h1>",
   "",
   "<h1 class=\"orange-text\">I am orange!</h1>"
  ]
 },
 {
  "name": "34 Use Abbreviated Hex Code",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: #F00;",
   "  }",
   "  .fuchsia-text {",
   "    color: #F0F;",
   "  }",
   "  .cyan-text {",
   "    color: #0FF;",
   "  }",
   "  .green-text {",
   "    color: #0F0;",
   "  }",
   "</style>",
   "",
   "<h1 class=\"red-text\">I am red!</h1>",
   "",
   "<h1 class=\"fuchsia-text\">I am fuchsia!</h1>",
   "",
   "<h1 class=\"cyan-text\">I am cyan!</h1>",
   "",
   "<h1 class=\"green-text\">I am green!</h1>"
  ]
 },
 {
  "name": "35 Use RGB values to Color Elements",
  "code": [
   "<style>",
   "  body {",
   "    background-color: rgb(0, 0, 0);",
   "  }",
   "</style>"
  ]
 },
 {
  "name": "36 Use RGB to Mix Colors",
  "code": [
   "<style>",
   "  .red-text {",
   "    color: rgb(255, 0, 0);",
   "  }",
   "  .orchid-text {",
   "    color: rgb(218, 112, 214);",
   "  }",
   "  .sienna-text {",
   "    color: rgb(160, 82, 45);",
   "  }",
   "  .blue-text {",
   "    color: rgb(0, 0, 255);",
   "  }",
   "</style>",
   "",
   "<h1 class=\"red-text\">I am red!</h1>",
   "",
   "<h1 class=\"orchid-text\">I am orchid!</h1>",
   "",
   "<h1 class=\"sienna-text\">I am sienna!</h1>",
   "",
   "<h1 class=\"blue-text\">I am blue!</h1>"
  ]
 },
 {
  "name": "37 Use CSS Variables to change several elements at once",
  "code": [
   "<style>",
   "  .penguin {",
   "",
   "    /* Only change code below this line */",
   "    --penguin-skin: gray;",
   "    --penguin-belly: white;",
   "    --penguin-beak: orange;",
   "    /* Only change code above this line */",
   "",
   "    position: relative;",
   "    margin: auto;",
   "    display: block;",
   "    margin-top: 5%;",
   "    width: 300px;",
   "    height: 300px;",
   "  }",
   "",
   "  .penguin-top {",
   "    top: 10%;",
   "    left: 25%;",
   "    background: var(--penguin-skin, gray);",
   "    width: 50%;",
   "    height: 45%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .penguin-bottom {",
   "    top: 40%;",
   "    left: 23.5%;",
   "    background: var(--penguin-skin, gray);",
   "    width: 53%;",
   "    height: 45%;",
   "    border-radius: 70% 70% 100% 100%;",
   "  }",
   "",
   "  .right-hand {",
   "    top: 0%;",
   "    left: -5%;",
   "    background: var(--penguin-skin, gray);",
   "    width: 30%;",
   "    height: 60%;",
   "    border-radius: 30% 30% 120% 30%;",
   "    transform: rotate(45deg);",
   "    z-index: -1;",
   "  }",
   "",
   "  .left-hand {",
   "    top: 0%;",
   "    left: 75%;",
   "    background: var(--penguin-skin, gray);",
   "    width: 30%;",
   "    height: 60%;",
   "    border-radius: 30% 30% 30% 120%;",
   "    transform: rotate(-45deg);",
   "    z-index: -1;",
   "  }",
   "",
   "  .right-cheek {",
   "    top: 15%;",
   "    left: 35%;",
   "    background: var(--penguin-belly, white);",
   "    width: 60%;",
   "    height: 70%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .left-cheek {",
   "    top: 15%;",
   "    left: 5%;",
   "    background: var(--penguin-belly, white);",
   "    width: 60%;",
   "    height: 70%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .belly {",
   "    top: 60%;",
   "    left: 2.5%;",
   "    background: var(--penguin-belly, white);",
   "    width: 95%;",
   "    height: 100%;",
   "    border-radius: 120% 120% 100% 100%;",
   "  }",
   "",
   "  .right-feet {",
   "    top: 85%;",
   "    left: 60%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 15%;",
   "    height: 30%;",
   "    border-radius: 50% 50% 50% 50%;",
   "    transform: rotate(-80deg);",
   "    z-index: -2222;",
   "  }",
   "",
   "  .left-feet {",
   "    top: 85%;",
   "    left: 25%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 15%;",
   "    height: 30%;",
   "    border-radius: 50% 50% 50% 50%;",
   "    transform: rotate(80deg);",
   "    z-index: -2222;",
   "  }",
   "",
   "  .right-eye {",
   "    top: 45%;",
   "    left: 60%;",
   "    background: black;",
   "    width: 15%;",
   "    height: 17%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .left-eye {",
   "    top: 45%;",
   "    left: 25%;",
   "    background: black;",
   "    width: 15%;",
   "    height: 17%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .sparkle {",
   "    top: 25%;",
   "    left: 15%;",
   "    background: white;",
   "    width: 35%;",
   "    height: 35%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .blush-right {",
   "    top: 65%;",
   "    left: 15%;",
   "    background: pink;",
   "    width: 15%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .blush-left {",
   "    top: 65%;",
   "    left: 70%;",
   "    background: pink;",
   "    width: 15%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .beak-top {",
   "    top: 60%;",
   "    left: 40%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 20%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .beak-bottom {",
   "    top: 65%;",
   "    left: 42%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 16%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  body {",
   "    background:#c6faf1;",
   "  }",
   "",
   "  .penguin * {",
   "    position: absolute;",
   "  }",
   "</style>",
   "<div class=\"penguin\">",
   "  <div class=\"penguin-bottom\">",
   "    <div class=\"right-hand\"></div>",
   "    <div class=\"left-hand\"></div>",
   "    <div class=\"right-feet\"></div>",
   "    <div class=\"left-feet\"></div>",
   "  </div>",
   "  <div class=\"penguin-top\">",
   "    <div class=\"right-cheek\"></div>",
   "    <div class=\"left-cheek\"></div>",
   "    <div class=\"belly\"></div>",
   "    <div class=\"right-eye\">",
   "      <div class=\"sparkle\"></div>",
   "    </div>",
   "    <div class=\"left-eye\">",
   "      <div class=\"sparkle\"></div>",
   "    </div>",
   "    <div class=\"blush-right\"></div>",
   "    <div class=\"blush-left\"></div>",
   "    <div class=\"beak-top\"></div>",
   "    <div class=\"beak-bottom\"></div>",
   "  </div>",
   "</div>"
  ]
 },
 {
  "name": "38 Create a custom CSS Variable",
  "code": [
   "    --penguin-skin: gray;",
   ""
  ]
 },
 {
  "name": "39 Use a custom CSS Variable",
  "code": [
   "<style>",
   "  .penguin {",
   "    --penguin-skin: gray;",
   "    position: relative;",
   "    margin: auto;",
   "    display: block;",
   "    margin-top: 5%;",
   "    width: 300px;",
   "    height: 300px;",
   "  }",
   "",
   "  .penguin-top {",
   "    top: 10%;",
   "    left: 25%;",
   "",
   "    /* Change code below this line */",
   "    background: var(--penguin-skin);",
   "    /* Change code above this line */",
   "",
   "    width: 50%;",
   "    height: 45%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .penguin-bottom {",
   "    top: 40%;",
   "    left: 23.5%;",
   "",
   "    /* Change code below this line */",
   "    background: var(--penguin-skin);",
   "    /* Change code above this line */",
   "",
   "    width: 53%;",
   "    height: 45%;",
   "    border-radius: 70% 70% 100% 100%;",
   "  }",
   "",
   "  .right-hand {",
   "    top: 0%;",
   "    left: -5%;",
   "",
   "    /* Change code below this line */",
   "    background: var(--penguin-skin);",
   "    /* Change code above this line */",
   "",
   "    width: 30%;",
   "    height: 60%;",
   "    border-radius: 30% 30% 120% 30%;",
   "    transform: rotate(45deg);",
   "    z-index: -1;",
   "  }",
   "",
   "  .left-hand {",
   "    top: 0%;",
   "    left: 75%;",
   "",
   "    /* Change code below this line */",
   "    background: var(--penguin-skin);",
   "    /* Change code above this line */",
   "",
   "    width: 30%;",
   "    height: 60%;",
   "    border-radius: 30% 30% 30% 120%;",
   "    transform: rotate(-45deg);",
   "    z-index: -1;",
   "  }",
   "",
   "  .right-cheek {",
   "    top: 15%;",
   "    left: 35%;",
   "    background: white;",
   "    width: 60%;",
   "    height: 70%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .left-cheek {",
   "    top: 15%;",
   "    left: 5%;",
   "    background: white;",
   "    width: 60%;",
   "    height: 70%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .belly {",
   "    top: 60%;",
   "    left: 2.5%;",
   "    background: white;",
   "    width: 95%;",
   "    height: 100%;",
   "    border-radius: 120% 120% 100% 100%;",
   "  }",
   "",
   "  .right-feet {",
   "    top: 85%;",
   "    left: 60%;",
   "    background: orange;",
   "    width: 15%;",
   "    height: 30%;",
   "    border-radius: 50% 50% 50% 50%;",
   "    transform: rotate(-80deg);",
   "    z-index: -2222;",
   "  }",
   "",
   "  .left-feet {",
   "    top: 85%;",
   "    left: 25%;",
   "    background: orange;",
   "    width: 15%;",
   "    height: 30%;",
   "    border-radius: 50% 50% 50% 50%;",
   "    transform: rotate(80deg);",
   "    z-index: -2222;",
   "  }",
   "",
   "  .right-eye {",
   "    top: 45%;",
   "    left: 60%;",
   "    background: black;",
   "    width: 15%;",
   "    height: 17%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .left-eye {",
   "    top: 45%;",
   "    left: 25%;",
   "    background: black;",
   "    width: 15%;",
   "    height: 17%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .sparkle {",
   "    top: 25%;",
   "    left: 15%;",
   "    background: white;",
   "    width: 35%;",
   "    height: 35%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .blush-right {",
   "    top: 65%;",
   "    left: 15%;",
   "    background: pink;",
   "    width: 15%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .blush-left {",
   "    top: 65%;",
   "    left: 70%;",
   "    background: pink;",
   "    width: 15%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .beak-top {",
   "    top: 60%;",
   "    left: 40%;",
   "    background: orange;",
   "    width: 20%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .beak-bottom {",
   "    top: 65%;",
   "    left: 42%;",
   "    background: orange;",
   "    width: 16%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  body {",
   "    background:#c6faf1;",
   "  }",
   "",
   "  .penguin * {",
   "    position: absolute;",
   "  }",
   "</style>",
   "<div class=\"penguin\">",
   "  <div class=\"penguin-bottom\">",
   "    <div class=\"right-hand\"></div>",
   "    <div class=\"left-hand\"></div>",
   "    <div class=\"right-feet\"></div>",
   "    <div class=\"left-feet\"></div>",
   "  </div>",
   "  <div class=\"penguin-top\">",
   "    <div class=\"right-cheek\"></div>",
   "    <div class=\"left-cheek\"></div>",
   "    <div class=\"belly\"></div>",
   "    <div class=\"right-eye\">",
   "      <div class=\"sparkle\"></div>",
   "    </div>",
   "    <div class=\"left-eye\">",
   "      <div class=\"sparkle\"></div>",
   "    </div>",
   "    <div class=\"blush-right\"></div>",
   "    <div class=\"blush-left\"></div>",
   "    <div class=\"beak-top\"></div>",
   "    <div class=\"beak-bottom\"></div>",
   "  </div>",
   "</div>"
  ]
 },
 {
  "name": "40 Attach a Fallback value to a CSS Variable",
  "code": [
   "<style>",
   "  .penguin {",
   "    --penguin-skin: black;",
   "    --penguin-belly: gray;",
   "    --penguin-beak: yellow;",
   "    position: relative;",
   "    margin: auto;",
   "    display: block;",
   "    margin-top: 5%;",
   "    width: 300px;",
   "    height: 300px;",
   "  }",
   "",
   "  .penguin-top {",
   "    top: 10%;",
   "    left: 25%;",
   "",
   "    /* Change code below this line */",
   "    background: var(--pengiun-skin, black);",
   "    /* Change code above this line */",
   "",
   "    width: 50%;",
   "    height: 45%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .penguin-bottom {",
   "    top: 40%;",
   "    left: 23.5%;",
   "",
   "    /* Change code below this line */",
   "    background: var(--pengiun-skin, black);",
   "    /* Change code above this line */",
   "",
   "    width: 53%;",
   "    height: 45%;",
   "    border-radius: 70% 70% 100% 100%;",
   "  }",
   "",
   "  .right-hand {",
   "    top: 0%;",
   "    left: -5%;",
   "    background: var(--penguin-skin, black);",
   "    width: 30%;",
   "    height: 60%;",
   "    border-radius: 30% 30% 120% 30%;",
   "    transform: rotate(45deg);",
   "    z-index: -1;",
   "  }",
   "",
   "  .left-hand {",
   "    top: 0%;",
   "    left: 75%;",
   "    background: var(--penguin-skin, black);",
   "    width: 30%;",
   "    height: 60%;",
   "    border-radius: 30% 30% 30% 120%;",
   "    transform: rotate(-45deg);",
   "    z-index: -1;",
   "  }",
   "",
   "  .right-cheek {",
   "    top: 15%;",
   "    left: 35%;",
   "    background: var(--penguin-belly, white);",
   "    width: 60%;",
   "    height: 70%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .left-cheek {",
   "    top: 15%;",
   "    left: 5%;",
   "    background: var(--penguin-belly, white);",
   "    width: 60%;",
   "    height: 70%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .belly {",
   "    top: 60%;",
   "    left: 2.5%;",
   "    background: var(--penguin-belly, white);",
   "    width: 95%;",
   "    height: 100%;",
   "    border-radius: 120% 120% 100% 100%;",
   "  }",
   "",
   "  .right-feet {",
   "    top: 85%;",
   "    left: 60%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 15%;",
   "    height: 30%;",
   "    border-radius: 50% 50% 50% 50%;",
   "    transform: rotate(-80deg);",
   "    z-index: -2222;",
   "  }",
   "",
   "  .left-feet {",
   "    top: 85%;",
   "    left: 25%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 15%;",
   "    height: 30%;",
   "    border-radius: 50% 50% 50% 50%;",
   "    transform: rotate(80deg);",
   "    z-index: -2222;",
   "  }",
   "",
   "  .right-eye {",
   "    top: 45%;",
   "    left: 60%;",
   "    background: black;",
   "    width: 15%;",
   "    height: 17%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .left-eye {",
   "    top: 45%;",
   "    left: 25%;",
   "    background: black;",
   "    width: 15%;",
   "    height: 17%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .sparkle {",
   "    top: 25%;",
   "    left: 15%;",
   "    background: white;",
   "    width: 35%;",
   "    height: 35%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .blush-right {",
   "    top: 65%;",
   "    left: 15%;",
   "    background: pink;",
   "    width: 15%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .blush-left {",
   "    top: 65%;",
   "    left: 70%;",
   "    background: pink;",
   "    width: 15%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .beak-top {",
   "    top: 60%;",
   "    left: 40%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 20%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .beak-bottom {",
   "    top: 65%;",
   "    left: 42%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 16%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  body {",
   "    background: #c6faf1;",
   "  }",
   "",
   "  .penguin * {",
   "    position: absolute;",
   "  }",
   "</style>",
   "<div class=\"penguin\">",
   "  <div class=\"penguin-bottom\">",
   "    <div class=\"right-hand\"></div>",
   "    <div class=\"left-hand\"></div>",
   "    <div class=\"right-feet\"></div>",
   "    <div class=\"left-feet\"></div>",
   "  </div>",
   "  <div class=\"penguin-top\">",
   "    <div class=\"right-cheek\"></div>",
   "    <div class=\"left-cheek\"></div>",
   "    <div class=\"belly\"></div>",
   "    <div class=\"right-eye\">",
   "      <div class=\"sparkle\"></div>",
   "    </div>",
   "    <div class=\"left-eye\">",
   "      <div class=\"sparkle\"></div>",
   "    </div>",
   "    <div class=\"blush-right\"></div>",
   "    <div class=\"blush-left\"></div>",
   "    <div class=\"beak-top\"></div>",
   "    <div class=\"beak-bottom\"></div>",
   "  </div>",
   "</div>"
  ]
 },
 {
  "name": "41 Improve Compatibility with Browser Fallbacks",
  "code": [
   "<style>",
   "  :root {",
   "    --red-color: red;",
   "  }",
   "  .red-box {",
   "    background: red;",
   "",
   "    background: var(--red-color);",
   "    height: 200px;",
   "    width:200px;",
   "  }",
   "</style>",
   "<div class=\"red-box\"></div>"
  ]
 },
 {
  "name": "42 Inherit CSS Variables",
  "code": [
   "  :root {",
   "    /* Only change code below this line */",
   "",
   "--penguin-belly: pink;",
   "",
   "    /* Only change code above this line */",
   "  }",
   ""
  ]
 },
 {
  "name": "43 Change a variable for a specific area",
  "code": [
   "  :root {",
   "    --penguin-skin: gray;",
   "    --penguin-belly: pink;",
   "    --penguin-beak: orange;",
   "  }",
   "",
   "  body {",
   "    background: var(--penguin-belly, #c6faf1);",
   "  }",
   "",
   "  .penguin {",
   "    /* Only change code below this line */",
   "--penguin-belly: white;",
   "    /* Only change code above this line */",
   "    position: relative;",
   "    margin: auto;",
   "    display: block;",
   "    margin-top: 5%;",
   "    width: 300px;",
   "    height: 300px;",
   "  }",
   ""
  ]
 },
 {
  "name": "44 Use a media query to change a variable",
  "code": [
   "<style>",
   "  :root {",
   "    --penguin-size: 300px;",
   "    --penguin-skin: gray;",
   "    --penguin-belly: white;",
   "    --penguin-beak: orange;",
   "  }",
   "",
   "  @media (max-width: 350px) {",
   "    :root {",
   "      /* Only change code below this line */",
   "--penguin-size: 200px;",
   "--penguin-skin: black;",
   "      /* Only change code above this line */",
   "    }",
   "  }",
   "",
   "  .penguin {",
   "    position: relative;",
   "    margin: auto;",
   "    display: block;",
   "    margin-top: 5%;",
   "    width: var(--penguin-size, 300px);",
   "    height: var(--penguin-size, 300px);",
   "  }",
   "",
   "  .right-cheek {",
   "    top: 15%;",
   "    left: 35%;",
   "    background: var(--penguin-belly, white);",
   "    width: 60%;",
   "    height: 70%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .left-cheek {",
   "    top: 15%;",
   "    left: 5%;",
   "    background: var(--penguin-belly, white);",
   "    width: 60%;",
   "    height: 70%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .belly {",
   "    top: 60%;",
   "    left: 2.5%;",
   "    background: var(--penguin-belly, white);",
   "    width: 95%;",
   "    height: 100%;",
   "    border-radius: 120% 120% 100% 100%;",
   "  }",
   "",
   "  .penguin-top {",
   "    top: 10%;",
   "    left: 25%;",
   "    background: var(--penguin-skin, gray);",
   "    width: 50%;",
   "    height: 45%;",
   "    border-radius: 70% 70% 60% 60%;",
   "  }",
   "",
   "  .penguin-bottom {",
   "    top: 40%;",
   "    left: 23.5%;",
   "    background: var(--penguin-skin, gray);",
   "    width: 53%;",
   "    height: 45%;",
   "    border-radius: 70% 70% 100% 100%;",
   "  }",
   "",
   "  .right-hand {",
   "    top: 5%;",
   "    left: 25%;",
   "    background: var(--penguin-skin, black);",
   "    width: 30%;",
   "    height: 60%;",
   "    border-radius: 30% 30% 120% 30%;",
   "    transform: rotate(130deg);",
   "    z-index: -1;",
   "    animation-duration: 3s;",
   "    animation-name: wave;",
   "    animation-iteration-count: infinite;",
   "    transform-origin:0% 0%;",
   "    animation-timing-function: linear;",
   "  }",
   "",
   "  @keyframes wave {",
   "      10% {",
   "        transform: rotate(110deg);",
   "      }",
   "      20% {",
   "        transform: rotate(130deg);",
   "      }",
   "      30% {",
   "        transform: rotate(110deg);",
   "      }",
   "      40% {",
   "        transform: rotate(130deg);",
   "      }",
   "    }",
   "",
   "  .left-hand {",
   "    top: 0%;",
   "    left: 75%;",
   "    background: var(--penguin-skin, gray);",
   "    width: 30%;",
   "    height: 60%;",
   "    border-radius: 30% 30% 30% 120%;",
   "    transform: rotate(-45deg);",
   "    z-index: -1;",
   "  }",
   "",
   "  .right-feet {",
   "    top: 85%;",
   "    left: 60%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 15%;",
   "    height: 30%;",
   "    border-radius: 50% 50% 50% 50%;",
   "    transform: rotate(-80deg);",
   "    z-index: -2222;",
   "  }",
   "",
   "  .left-feet {",
   "    top: 85%;",
   "    left: 25%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 15%;",
   "    height: 30%;",
   "    border-radius: 50% 50% 50% 50%;",
   "    transform: rotate(80deg);",
   "    z-index: -2222;",
   "  }",
   "",
   "  .right-eye {",
   "    top: 45%;",
   "    left: 60%;",
   "    background: black;",
   "    width: 15%;",
   "    height: 17%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .left-eye {",
   "    top: 45%;",
   "    left: 25%;",
   "    background: black;",
   "    width: 15%;",
   "    height: 17%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .sparkle {",
   "    top: 25%;",
   "    left:-23%;",
   "    background: white;",
   "    width: 150%;",
   "    height: 100%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .blush-right {",
   "    top: 65%;",
   "    left: 15%;",
   "    background: pink;",
   "    width: 15%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .blush-left {",
   "    top: 65%;",
   "    left: 70%;",
   "    background: pink;",
   "    width: 15%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .beak-top {",
   "    top: 60%;",
   "    left: 40%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 20%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  .beak-bottom {",
   "    top: 65%;",
   "    left: 42%;",
   "    background: var(--penguin-beak, orange);",
   "    width: 16%;",
   "    height: 10%;",
   "    border-radius: 50%;",
   "  }",
   "",
   "  body {",
   "    background:#c6faf1;",
   "  }",
   "",
   "  .penguin * {",
   "    position: absolute;",
   "  }",
   "</style>",
   "<div class=\"penguin\">",
   "  <div class=\"penguin-bottom\">",
   "    <div class=\"right-hand\"></div>",
   "    <div class=\"left-hand\"></div>",
   "    <div class=\"right-feet\"></div>",
   "    <div class=\"left-feet\"></div>",
   "  </div>",
   "  <div class=\"penguin-top\">",
   "    <div class=\"right-cheek\"></div>",
   "    <div class=\"left-cheek\"></div>",
   "    <div class=\"belly\"></div>",
   "    <div class=\"right-eye\">",
   "      <div class=\"sparkle\"></div>",
   "    </div>",
   "    <div class=\"left-eye\">",
   "      <div class=\"sparkle\"></div>",
   "    </div>",
   "    <div class=\"blush-right\"></div>",
   "    <div class=\"blush-left\"></div>",
   "    <div class=\"beak-top\"></div>",
   "    <div class=\"beak-bottom\"></div>",
   "  </div>",
   "</div>"
  ]
 }
]

